{% set name = "fgivenx" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fgivenx-{{ version }}.tar.gz
  sha256: df3c4593744b106ca28f9b43fe4038dcbea9240f249bc0b647e5d6ae3b7626ca

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - scipy

test:
  requires:
    # https://github.com/handley-lab/fgivenx/issues/22
    - matplotlib-base <3.8.0a0
    - pip
    - pytest
    - pytest-mpl
    - python {{ python_min }}
  commands:
    - python -m pip check
    - python -m pip show fgivenx
    - python -m pytest -ra -v --pyargs fgivenx

about:
  home: https://github.com/williamjameshandley/fgivenx
  doc_url: http://fgivenx.readthedocs.io/
  summary: Functional Posterior Plotter
  license: MIT
  license_file: LICENSE.txt
  description: |
    fgivenx is a python package for plotting posteriors of functions.
    It is currently used in astronomy, but will be of use to any
    scientists performing Bayesian analyses which have predictive
    posteriors that are functions.

    This package allows one to plot a predictive posterior of a function,
    dependent on sampled parameters.
    We assume one has a Bayesian posterior `Post(theta|D,M)` described by a
    set of posterior samples `{theta_i}~Post`.
    If there is a function parameterised by theta `y=f(x;theta)`, then this
    script will produce a contour plot of the conditional posterior
    `P(y|x,D,M)` in the `(x,y)` plane.

    The driving routines are `fgivenx.plot_contours`, `fgivenx.plot_lines`
    and `fgivenx.plot_dkl`.
    The code is compatible with `getdist`, and has a loading function
    provided by `fgivenx.samples_from_getdist_chains`.

extra:
  recipe-maintainers:
    - duncanmmacleod
